// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/cluster/pb/stream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeMessage is sent agent -> coordinator over the persistent stream.
type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*NodeMessage_Heartbeat
	//	*NodeMessage_Progress
	Kind          isNodeMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_pb_stream_proto_rawDescGZIP(), []int{0}
}

func (x *NodeMessage) GetKind() isNodeMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *NodeMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Kind.(*NodeMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *NodeMessage) GetProgress() *JobProgressUpdate {
	if x != nil {
		if x, ok := x.Kind.(*NodeMessage_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isNodeMessage_Kind interface {
	isNodeMessage_Kind()
}

type NodeMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type NodeMessage_Progress struct {
	Progress *JobProgressUpdate `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

func (*NodeMessage_Heartbeat) isNodeMessage_Kind() {}

func (*NodeMessage_Progress) isNodeMessage_Kind() {}

// CoordinatorMessage is pushed coordinator -> agent over the same stream.
type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*CoordinatorMessage_Ack
	//	*CoordinatorMessage_RunJob
	//	*CoordinatorMessage_InstallTools
	Kind          isCoordinatorMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_pb_stream_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinatorMessage) GetKind() isCoordinatorMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *CoordinatorMessage) GetAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Kind.(*CoordinatorMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetRunJob() *RunIngestJob {
	if x != nil {
		if x, ok := x.Kind.(*CoordinatorMessage_RunJob); ok {
			return x.RunJob
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetInstallTools() *InstallTools {
	if x != nil {
		if x, ok := x.Kind.(*CoordinatorMessage_InstallTools); ok {
			return x.InstallTools
		}
	}
	return nil
}

type isCoordinatorMessage_Kind interface {
	isCoordinatorMessage_Kind()
}

type CoordinatorMessage_Ack struct {
	Ack *HeartbeatAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type CoordinatorMessage_RunJob struct {
	RunJob *RunIngestJob `protobuf:"bytes,2,opt,name=run_job,json=runJob,proto3,oneof"`
}

type CoordinatorMessage_InstallTools struct {
	InstallTools *InstallTools `protobuf:"bytes,3,opt,name=install_tools,json=installTools,proto3,oneof"`
}

func (*CoordinatorMessage_Ack) isCoordinatorMessage_Kind() {}

func (*CoordinatorMessage_RunJob) isCoordinatorMessage_Kind() {}

func (*CoordinatorMessage_InstallTools) isCoordinatorMessage_Kind() {}

type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os             string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Platform       string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Ips            []string               `protobuf:"bytes,5,rep,name=ips,proto3" json:"ips,omitempty"`
	UptimeSec      uint64                 `protobuf:"varint,6,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	Disks          []*DiskStat            `protobuf:"bytes,7,rep,name=disks,proto3" json:"disks,omitempty"`
	Memory         *MemoryStat            `protobuf:"bytes,8,opt,name=memory,proto3" json:"memory,omitempty"`
	Cpu            *CPUStat               `protobuf:"bytes,9,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Capabilities   *NodeCapabilities      `protobuf:"bytes,10,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	ReportedAtUnix int64                  `protobuf:"varint,11,opt,name=reported_at_unix,json=reportedAtUnix,proto3" json:"reported_at_unix,omitempty"`
	// Resolved on-disk media storage location (best mount picked at startup).
	MediaPath     string `protobuf:"bytes,12,opt,name=media_path,json=mediaPath,proto3" json:"media_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_pb_stream_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Heartbeat) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Heartbeat) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Heartbeat) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *Heartbeat) GetUptimeSec() uint64 {
	if x != nil {
		return x.UptimeSec
	}
	return 0
}

func (x *Heartbeat) GetDisks() []*DiskStat {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *Heartbeat) GetMemory() *MemoryStat {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *Heartbeat) GetCpu() *CPUStat {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Heartbeat) GetCapabilities() *NodeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Heartbeat) GetReportedAtUnix() int64 {
	if x != nil {
		return x.ReportedAtUnix
	}
	return 0
}

func (x *Heartbeat) GetMediaPath() string {
	if x != nil {
		return x.MediaPath
	}
	return ""
}

type DiskStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	FsType        string                 `protobuf:"bytes,2,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	DiskType      string                 `protobuf:"bytes,3,opt,name=disk_type,json=diskType,proto3" json:"disk_type,omitempty"` // "SSD", "HDD", "NVMe"
	TotalBytes    uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,5,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,6,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,7,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskStat) Reset() {
	*x = DiskStat{}
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskStat) ProtoMessage() {}

func (x *DiskStat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskStat.ProtoReflect.Descriptor instead.
func (*DiskStat) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_pb_stream_proto_rawDescGZIP(), []int{3}
}

func (x *DiskStat) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskStat) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *DiskStat) GetDiskType() string {
	if x != nil {
		return x.DiskType
	}
	return ""
}

func (x *DiskStat) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskStat) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *DiskStat) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskStat) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

type MemoryStat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalBytes     uint64                 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	AvailableBytes uint64                 `protobuf:"varint,2,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	UsedBytes      uint64                 `protobuf:"varint,3,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	UsedPercent    float64                `protobuf:"fixed64,4,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryStat) Reset() {
	*x = MemoryStat{}
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStat) ProtoMessage() {}

func (x *MemoryStat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStat.ProtoReflect.Descriptor instead.
func (*MemoryStat) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_pb_stream_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryStat) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MemoryStat) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *MemoryStat) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *MemoryStat) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

type CPUStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cores         int32                  `protobuf:"varint,1,opt,name=cores,proto3" json:"cores,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,3,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUStat) Reset() {
	*x = CPUStat{}
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUStat) ProtoMessage() {}

func (x *CPUStat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUStat.ProtoReflect.Descriptor instead.
func (*CPUStat) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_pb_stream_proto_rawDescGZIP(), []int{5}
}

func (x *CPUStat) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPUStat) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CPUStat) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

type NodeCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasFfmpeg     bool                   `protobuf:"varint,1,opt,name=has_ffmpeg,json=hasFfmpeg,proto3" json:"has_ffmpeg,omitempty"`
	HasAria2C     bool                   `protobuf:"varint,2,opt,name=has_aria2c,json=hasAria2c,proto3" json:"has_aria2c,omitempty"`
	AgentPort     int32                  `protobuf:"varint,3,opt,name=agent_port,json=agentPort,proto3" json:"agent_port,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCapabilities) Reset() {
	*x = NodeCapabilities{}
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapabilities) ProtoMessage() {}

func (x *NodeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapabilities.ProtoReflect.Descriptor instead.
func (*NodeCapabilities) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_pb_stream_proto_rawDescGZIP(), []int{6}
}

func (x *NodeCapabilities) GetHasFfmpeg() bool {
	if x != nil {
		return x.HasFfmpeg
	}
	return false
}

func (x *NodeCapabilities) GetHasAria2C() bool {
	if x != nil {
		return x.HasAria2C
	}
	return false
}

func (x *NodeCapabilities) GetAgentPort() int32 {
	if x != nil {
		return x.AgentPort
	}
	return 0
}

func (x *NodeCapabilities) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type JobProgressUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // queued|downloading|packaging|completed|failed
	ProgressPercent float64                `protobuf:"fixed64,3,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	DownloadSpeed   string                 `protobuf:"bytes,4,opt,name=download_speed,json=downloadSpeed,proto3" json:"download_speed,omitempty"`
	ErrorMsg        string                 `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	// CMAF package payload serialized as JSON; it is display data, not control
	// data, so it stays schema-free to avoid coupling the wire format to the
	// media packaging structs.
	CmafJson      []byte `protobuf:"bytes,6,opt,name=cmaf_json,json=cmafJson,proto3" json:"cmaf_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobProgressUpdate) Reset() {
	*x = JobProgressUpdate{}
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobProgressUpdate) ProtoMessage() {}

func (x *JobProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobProgressUpdate.ProtoReflect.Descriptor instead.
func (*JobProgressUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_pb_stream_proto_rawDescGZIP(), []int{7}
}

func (x *JobProgressUpdate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobProgressUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobProgressUpdate) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *JobProgressUpdate) GetDownloadSpeed() string {
	if x != nil {
		return x.DownloadSpeed
	}
	return ""
}

func (x *JobProgressUpdate) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *JobProgressUpdate) GetCmafJson() []byte {
	if x != nil {
		return x.CmafJson
	}
	return nil
}

type HeartbeatAck struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// false when the node has been decommissioned; the agent must disconnect.
	NodeEnabled         bool   `protobuf:"varint,3,opt,name=node_enabled,json=nodeEnabled,proto3" json:"node_enabled,omitempty"`
	LatestVersion       string `protobuf:"bytes,4,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	DownloadUrl         string `protobuf:"bytes,5,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	UpdateAvailable     bool   `protobuf:"varint,6,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"`
	InstallMissingTools bool   `protobuf:"varint,7,opt,name=install_missing_tools,json=installMissingTools,proto3" json:"install_missing_tools,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_pb_stream_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatAck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatAck) GetNodeEnabled() bool {
	if x != nil {
		return x.NodeEnabled
	}
	return false
}

func (x *HeartbeatAck) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *HeartbeatAck) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *HeartbeatAck) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

func (x *HeartbeatAck) GetInstallMissingTools() bool {
	if x != nil {
		return x.InstallMissingTools
	}
	return false
}

type RunIngestJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,2,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunIngestJob) Reset() {
	*x = RunIngestJob{}
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunIngestJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunIngestJob) ProtoMessage() {}

func (x *RunIngestJob) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunIngestJob.ProtoReflect.Descriptor instead.
func (*RunIngestJob) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_pb_stream_proto_rawDescGZIP(), []int{9}
}

func (x *RunIngestJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunIngestJob) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

type InstallTools struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallTools) Reset() {
	*x = InstallTools{}
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallTools) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallTools) ProtoMessage() {}

func (x *InstallTools) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_pb_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallTools.ProtoReflect.Descriptor instead.
func (*InstallTools) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_pb_stream_proto_rawDescGZIP(), []int{10}
}

var File_pkg_cluster_pb_stream_proto protoreflect.FileDescriptor

const file_pkg_cluster_pb_stream_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/cluster/pb/stream.proto\x12\tstream_pb\"\x87\x01\n" +
	"\vNodeMessage\x124\n" +
	"\theartbeat\x18\x01 \x01(\v2\x14.stream_pb.HeartbeatH\x00R\theartbeat\x12:\n" +
	"\bprogress\x18\x02 \x01(\v2\x1c.stream_pb.JobProgressUpdateH\x00R\bprogressB\x06\n" +
	"\x04kind\"\xbd\x01\n" +
	"\x12CoordinatorMessage\x12+\n" +
	"\x03ack\x18\x01 \x01(\v2\x17.stream_pb.HeartbeatAckH\x00R\x03ack\x122\n" +
	"\arun_job\x18\x02 \x01(\v2\x17.stream_pb.RunIngestJobH\x00R\x06runJob\x12>\n" +
	"\rinstall_tools\x18\x03 \x01(\v2\x17.stream_pb.InstallToolsH\x00R\finstallToolsB\x06\n" +
	"\x04kind\"\xa7\x03\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x10\n" +
	"\x03ips\x18\x05 \x03(\tR\x03ips\x12\x1d\n" +
	"\n" +
	"uptime_sec\x18\x06 \x01(\x04R\tuptimeSec\x12)\n" +
	"\x05disks\x18\a \x03(\v2\x13.stream_pb.DiskStatR\x05disks\x12-\n" +
	"\x06memory\x18\b \x01(\v2\x15.stream_pb.MemoryStatR\x06memory\x12$\n" +
	"\x03cpu\x18\t \x01(\v2\x12.stream_pb.CPUStatR\x03cpu\x12?\n" +
	"\fcapabilities\x18\n" +
	" \x01(\v2\x1b.stream_pb.NodeCapabilitiesR\fcapabilities\x12(\n" +
	"\x10reported_at_unix\x18\v \x01(\x03R\x0ereportedAtUnix\x12\x1d\n" +
	"\n" +
	"media_path\x18\f \x01(\tR\tmediaPath\"\xd6\x01\n" +
	"\bDiskStat\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x17\n" +
	"\afs_type\x18\x02 \x01(\tR\x06fsType\x12\x1b\n" +
	"\tdisk_type\x18\x03 \x01(\tR\bdiskType\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x05 \x01(\x04R\tfreeBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x06 \x01(\x04R\tusedBytes\x12!\n" +
	"\fused_percent\x18\a \x01(\x01R\vusedPercent\"\x98\x01\n" +
	"\n" +
	"MemoryStat\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x04R\n" +
	"totalBytes\x12'\n" +
	"\x0favailable_bytes\x18\x02 \x01(\x04R\x0eavailableBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x03 \x01(\x04R\tusedBytes\x12!\n" +
	"\fused_percent\x18\x04 \x01(\x01R\vusedPercent\"a\n" +
	"\aCPUStat\x12\x14\n" +
	"\x05cores\x18\x01 \x01(\x05R\x05cores\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12!\n" +
	"\fused_percent\x18\x03 \x01(\x01R\vusedPercent\"\x89\x01\n" +
	"\x10NodeCapabilities\x12\x1d\n" +
	"\n" +
	"has_ffmpeg\x18\x01 \x01(\bR\thasFfmpeg\x12\x1d\n" +
	"\n" +
	"has_aria2c\x18\x02 \x01(\bR\thasAria2c\x12\x1d\n" +
	"\n" +
	"agent_port\x18\x03 \x01(\x05R\tagentPort\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xce\x01\n" +
	"\x11JobProgressUpdate\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10progress_percent\x18\x03 \x01(\x01R\x0fprogressPercent\x12%\n" +
	"\x0edownload_speed\x18\x04 \x01(\tR\rdownloadSpeed\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\x12\x1b\n" +
	"\tcmaf_json\x18\x06 \x01(\fR\bcmafJson\"\x8b\x02\n" +
	"\fHeartbeatAck\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fnode_enabled\x18\x03 \x01(\bR\vnodeEnabled\x12%\n" +
	"\x0elatest_version\x18\x04 \x01(\tR\rlatestVersion\x12!\n" +
	"\fdownload_url\x18\x05 \x01(\tR\vdownloadUrl\x12)\n" +
	"\x10update_available\x18\x06 \x01(\bR\x0fupdateAvailable\x122\n" +
	"\x15install_missing_tools\x18\a \x01(\bR\x13installMissingTools\"D\n" +
	"\fRunIngestJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"source_url\x18\x02 \x01(\tR\tsourceUrl\"\x0e\n" +
	"\fInstallTools2P\n" +
	"\x04Mesh\x12H\n" +
	"\vNodeChannel\x12\x16.stream_pb.NodeMessage\x1a\x1d.stream_pb.CoordinatorMessage(\x010\x01B\x17Z\x15stream/pkg/cluster/pbb\x06proto3"

var (
	file_pkg_cluster_pb_stream_proto_rawDescOnce sync.Once
	file_pkg_cluster_pb_stream_proto_rawDescData []byte
)

func file_pkg_cluster_pb_stream_proto_rawDescGZIP() []byte {
	file_pkg_cluster_pb_stream_proto_rawDescOnce.Do(func() {
		file_pkg_cluster_pb_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_cluster_pb_stream_proto_rawDesc), len(file_pkg_cluster_pb_stream_proto_rawDesc)))
	})
	return file_pkg_cluster_pb_stream_proto_rawDescData
}

var file_pkg_cluster_pb_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_cluster_pb_stream_proto_goTypes = []any{
	(*NodeMessage)(nil),        // 0: stream_pb.NodeMessage
	(*CoordinatorMessage)(nil), // 1: stream_pb.CoordinatorMessage
	(*Heartbeat)(nil),          // 2: stream_pb.Heartbeat
	(*DiskStat)(nil),           // 3: stream_pb.DiskStat
	(*MemoryStat)(nil),         // 4: stream_pb.MemoryStat
	(*CPUStat)(nil),            // 5: stream_pb.CPUStat
	(*NodeCapabilities)(nil),   // 6: stream_pb.NodeCapabilities
	(*JobProgressUpdate)(nil),  // 7: stream_pb.JobProgressUpdate
	(*HeartbeatAck)(nil),       // 8: stream_pb.HeartbeatAck
	(*RunIngestJob)(nil),       // 9: stream_pb.RunIngestJob
	(*InstallTools)(nil),       // 10: stream_pb.InstallTools
}
var file_pkg_cluster_pb_stream_proto_depIdxs = []int32{
	2,  // 0: stream_pb.NodeMessage.heartbeat:type_name -> stream_pb.Heartbeat
	7,  // 1: stream_pb.NodeMessage.progress:type_name -> stream_pb.JobProgressUpdate
	8,  // 2: stream_pb.CoordinatorMessage.ack:type_name -> stream_pb.HeartbeatAck
	9,  // 3: stream_pb.CoordinatorMessage.run_job:type_name -> stream_pb.RunIngestJob
	10, // 4: stream_pb.CoordinatorMessage.install_tools:type_name -> stream_pb.InstallTools
	3,  // 5: stream_pb.Heartbeat.disks:type_name -> stream_pb.DiskStat
	4,  // 6: stream_pb.Heartbeat.memory:type_name -> stream_pb.MemoryStat
	5,  // 7: stream_pb.Heartbeat.cpu:type_name -> stream_pb.CPUStat
	6,  // 8: stream_pb.Heartbeat.capabilities:type_name -> stream_pb.NodeCapabilities
	0,  // 9: stream_pb.Mesh.NodeChannel:input_type -> stream_pb.NodeMessage
	1,  // 10: stream_pb.Mesh.NodeChannel:output_type -> stream_pb.CoordinatorMessage
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_cluster_pb_stream_proto_init() }
func file_pkg_cluster_pb_stream_proto_init() {
	if File_pkg_cluster_pb_stream_proto != nil {
		return
	}
	file_pkg_cluster_pb_stream_proto_msgTypes[0].OneofWrappers = []any{
		(*NodeMessage_Heartbeat)(nil),
		(*NodeMessage_Progress)(nil),
	}
	file_pkg_cluster_pb_stream_proto_msgTypes[1].OneofWrappers = []any{
		(*CoordinatorMessage_Ack)(nil),
		(*CoordinatorMessage_RunJob)(nil),
		(*CoordinatorMessage_InstallTools)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_cluster_pb_stream_proto_rawDesc), len(file_pkg_cluster_pb_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_cluster_pb_stream_proto_goTypes,
		DependencyIndexes: file_pkg_cluster_pb_stream_proto_depIdxs,
		MessageInfos:      file_pkg_cluster_pb_stream_proto_msgTypes,
	}.Build()
	File_pkg_cluster_pb_stream_proto = out.File
	file_pkg_cluster_pb_stream_proto_goTypes = nil
	file_pkg_cluster_pb_stream_proto_depIdxs = nil
}
